2024-10-29 01:36:18 - INFO - __main__ - Initializing training script
2024-10-29 01:36:18 - INFO - __main__ - Loading dataset...
2024-10-29 01:36:18 - INFO - __main__ - Loading model and tokenizer...
config.json: 100%|███████████████████████████████████████████████████| 481/481 [00:00<00:00, 1.58MB/s]
tokenizer_config.json: 100%|███████████████████████████████████████| 25.0/25.0 [00:00<00:00, 55.0kB/s]
vocab.json: 899kB [00:00, 2.08MB/s]
merges.txt: 456kB [00:00, 1.12MB/s]
tokenizer.json: 1.36MB [00:00, 1.81MB/s]
Traceback (most recent call last):
  File "/root/HW2/task2/train.py", line 70, in <module>
    model = AutoModelForSequenceClassification.from_pretrained(model_args.model_name_or_path, config=config)
  File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1651, in __getattribute__
    requires_backends(cls, cls._backends)
  File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1639, in requires_backends
    raise ImportError("".join(failed))
ImportError:
AutoModelForSequenceClassification requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.
